-- Default per-tenant database initialization (baseline profile).
-- Runs FIRST on a fresh Postgres volume (docker-entrypoint-initdb.d, 01-init.sql).
-- A tenant can override it with tenants-config/<slug>/init.sql.
--
-- Static defaults are intentionally minimal:
--   - schemas/roles/tables for dedicated app modules are GENERATED per tenant
--     with real credentials (02-modules.sql, provision/deploy pipeline)
--   - portal-owned DDL is applied by Flyway at boot (advisory lock + schema history)
--   - Keycloak does not use Postgres in tenant deployments (dev-file DB)
